version: '3.5'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster-7
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - ${JAVA_OPTS}
    labels:
      co.elastic.metrics/raw: "[{\"metricsets\":[\"node_stats\",\"node\"],\"module\":\"elasticsearch\",\"hosts\":\"http://es01:9200\"},{\"metricsets\":[\"cpu\"],\"module\":\"system\"}]"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 200000
        hard: 200000
    ports:
      - 9200:9200
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    networks:
      - es-network
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-cluster-7
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - ${JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 200000
        hard: 200000
    volumes:
      - es-data02:/usr/share/elasticsearch/data
    networks:
      - es-network
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-cluster-7
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - ${JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 200000
        hard: 200000
    volumes:
      - es-data03:/usr/share/elasticsearch/data
    networks:
      - es-network

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}
    ports:
      - 80:5601
      - 5601:5601
    networks:
      - es-network
    depends_on:
      - es01

#  filebeat:
#    build: 
#      context: filebeat/
#      args:
#        ELK_VERSION: ${ELK_VERSION}
#    image: hint-enabled-filebeat:${ELK_VERSION}
#    user: root
#    environment:
#      ELASTICSEARCH_HOSTS: http://node01:9200
#      KIBANA_HOSTS: http://kibana:5601
#    volumes:
#      - filebeat-data01:/usr/share/filebeat/data
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - es-network
#    depends_on:
#      - node01
#      - kibana

  metricbeat:
    build: 
      context: metricbeat/
      args:
        ELK_VERSION: ${ELK_VERSION}
    image: vot-metricbeat:${ELK_VERSION}
    user: root
    environment:
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS} 
      KIBANA_HOSTS: ${KIBANA_HOSTS}
    volumes:
      - metricbeat-data01:/usr/share/metricbeat/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - es-network
    depends_on:
      - es01

volumes:
  es-data01:
    driver_opts:
      type: none
      o: bind
      device: /var/elk/data/01
  es-data02:
    driver_opts:
      type: none
      o: bind
      device: /var/elk/data/01
  es-data03:
    driver_opts:
      type: none
      o: bind
      device: /var/elk/data/01
  metricbeat-data01:
    driver: local

  #filebeat-data01:
  #  driver: local

networks:
  es-network:
    driver: bridge
