version: '3.5'
services:
  node01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: node01
    environment:
      - node.name=node01
      - cluster.name=es-cluster-7
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    labels:
      co.elastic.metrics/module: "elasticsearch"
      co.elastic.metrics/hosts: "http://node01:9200"
      co.elastic.metrics/metricsets: "node_stats,node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es-network

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://node01:9200
    ports:
      - 5601:5601
    networks:
      - es-network
    depends_on:
      - node01

  filebeat:
    build: 
      context: filebeat/
      args:
        ELK_VERSION: ${ELK_VERSION}
    image: hint-enabled-filebeat:${ELK_VERSION}
    user: root
    environment:
      ELASTICSEARCH_HOSTS: http://node01:9200
      KIBANA_HOSTS: http://kibana:5601
    volumes:
      - filebeat-data01:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - es-network
    depends_on:
      - node01
      - kibana

  metricbeat:
    build: 
      context: metricbeat/
      args:
        ELK_VERSION: ${ELK_VERSION}
    image: hint-enabled-metricbeat:${ELK_VERSION}
    user: root
    environment:
      ELASTICSEARCH_HOSTS: http://node01:9200
    volumes:
      - metricbeat-data01:/usr/share/metricbeat/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - es-network
    depends_on:
      - node01

volumes:
  es-data01:
    driver: local
  metricbeat-data01:
    driver: local
  filebeat-data01:
    driver: local

networks:
  es-network:
    driver: bridge
