metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

setup.kibana:
  host: ${KIBANA_HOSTS:kibana:5601}

# enabled modules for monitoring (e.g. elasticsearch-xpack)
metricbeat.modules:
- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ${ELASTICSEARCH_HOSTS}
- module: system
  metricsets:
     - cpu
     - load
     - core
  cpu.metrics:
     - percentages
     - normalized_percentages
  enabled: true
  period: 10s

# adding hint support
metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
